// Generated by dia2code
#ifndef STATE__ARMY__H
#define STATE__ARMY__H


namespace state {
  class Element;
  class MobileElement;
}

#include "TypeID.h"
#include "MobileElement.h"

namespace state {

  /// class Army - 
  class Army : public state::MobileElement {
    // Attributes
  protected:
    int soldiers     = 0;
    // Operations
  public:
    TypeID getTypeID ();
    //bool const equals (const Element& other);
    Army ();
    bool const isMoving ();
    // Setters and Getters
    int getSoldiers() const;
    void setSoldiers(int soldiers);
  };

};

#endif
