// Generated by dia2code
#ifndef STATE__BARRACK__H
#define STATE__BARRACK__H


namespace state {
  class Construction;
}

#include "ConstructionTypeId.h"
#include "Construction.h"

namespace state {

  /// class Barrack - 
  class Barrack : public state::Construction {
    // Operations
  public:
    Barrack ();
    bool isProducing () const;
    ConstructionTypeId getConstructionId () const;
    int getSoldiersCost () const;
    int getSoldiersFood () const;
    // Setters and Getters
  };

};

#endif
