// Generated by dia2code
#ifndef STATE__CONSTRUCTIONTYPEID__H
#define STATE__CONSTRUCTIONTYPEID__H


namespace state {

  enum ConstructionTypeId {
    FARM     = 1,
    MINE     = 2,
    BARRACK     = 3
  };

};

#endif
