// Generated by dia2code
#ifndef STATE__CONSTRUCTION__H
#define STATE__CONSTRUCTION__H

#include <vector>

namespace state {

  /// class Construction - 
  class Construction {
    // Attributes
  public:
    int ressourcesToBuild;
    std::vector<int> list;
  private:
    int level     = 1;
    int productionByTurn;
    // Operations
  public:
    Construction ();
    virtual bool isProducing () = 0;
    // Setters and Getters
  };

};

#endif
