// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

#include "TypeID.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  protected:
    int x     = 0;
    int y     = 0;
    int idPlayer     = 0;
    // Operations
  public:
    Element ();
    virtual ~Element ();
    virtual TypeID getTypeID () const = 0;
    virtual bool const equals (const Element& other);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    int getIdPlayer() const;
    void setIdPlayer(int idPlayer);
  };

};

#endif
