// Generated by dia2code
#ifndef STATE__FARM__H
#define STATE__FARM__H


namespace state {
  class Construction;
}

#include "Construction.h"

namespace state {

  /// class Farm - 
  class Farm : public state::Construction {
    // Operations
  public:
    Farm ();
    bool isProducing () const;
    // Setters and Getters
  };

};

#endif
