// Generated by dia2code
#ifndef STATE__LANDSCAPE__H
#define STATE__LANDSCAPE__H


namespace state {
  class StaticElement;
}

#include "TypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Landscape - 
  class Landscape : public state::StaticElement {
    // Attributes
  protected:
    int type;
    // Operations
  public:
    Landscape ();
    bool  isAccessible () const;
    TypeID getTypeID () const;
    bool isInteractive () const;
    bool isStatic () const;
    Landscape (int type, bool accessible);
    // Setters and Getters
    int getType() const;
    void setType(int type);
  };

};

#endif
