// Generated by dia2code
#ifndef STATE__MINE__H
#define STATE__MINE__H


namespace state {
  class Construction;
}

#include "Construction.h"

namespace state {

  /// class Mine - 
  class Mine : public state::Construction {
    // Attributes
  public:
     ;
    // Operations
  public:
    bool isProducing ();
    Mine ();
    // Setters and Getters
  };

};

#endif
