// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Attributes
  protected:
    int range;
    bool moving;
    bool inCity;
    // Operations
  public:
    virtual bool isMoving () const = 0;
    MobileElement (int range = 0);
    // Setters and Getters
    int getRange() const;
    void setRange(int range);
    bool getMoving() const;
    void setMoving(bool moving);
    bool getInCity() const;
    void setInCity(bool inCity);
  };

};

#endif
