// Generated by dia2code
#ifndef STATE__MONDE__H
#define STATE__MONDE__H

#include <vector>

namespace state {
  class Layer;
  class Element;
}

#include "Layer.h"
#include "Element.h"

namespace state {

  /// class Monde - 
  class Monde {
    // Associations
    // Attributes
  private:
    int height;
    int width;
    int nbLayers;
    std::vector<Layer* > layers;
    // Operations
  public:
    Monde (int width, int height, int depth);
    virtual ~Monde ();
    void set (int x, int y, int layer, Element* e);
    Element* get (int x, int y, int layer) const;
    std::vector<Layer* > getLayers () const;
    int getWidth () const;
    int getHeight () const;
    Monde (int depth);
    // Setters and Getters
  };

};

#endif
