// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>

namespace state {

  /// class Player - 
  class Player {
    // Attributes
  public:
    bool playing     = false;
    int id;
  private:
    std::string name;
    int gold     = 0;
    int food     = 0;
    // Operations
  public:
    Player ();
    bool const isPlaying ();
    // Setters and Getters
  };

};

#endif
