// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>

namespace state {

  /// class Player - 
  class Player {
    // Attributes
  protected:
    std::string name;
    int gold;
    int food;
    bool playing;
    int id;
    // Operations
  public:
    Player ();
    Player (std::string nom);
    virtual ~Player ();
    bool isPlaying () const;
    // Setters and Getters
    const std::string& getName() const;
    void setName(const std::string& name);
    int getGold() const;
    void setGold(int gold);
    int getFood() const;
    void setFood(int food);
    bool getPlaying() const;
    void setPlaying(bool playing);
    int getId() const;
    void setId(int id);
  };

};

#endif
