// Generated by dia2code
#ifndef STATE__SETTLERS__H
#define STATE__SETTLERS__H


namespace state {
  class MobileElement;
}

#include "TypeID.h"
#include "MobileElement.h"

namespace state {

  /// class Settlers - 
  class Settlers : public state::MobileElement {
    // Operations
  public:
    Settlers ();
    virtual ~Settlers ();
    TypeID getTypeID () const;
    bool  isMoving () const;
    bool isInteractive () const;
    bool isInCity () const;
    bool isStatic () const;
    // Setters and Getters
  };

};

#endif
