// Generated by dia2code
#ifndef STATE__SETTLERS__H
#define STATE__SETTLERS__H


namespace state {
  class Element;
  class MobileElement;
}

#include "TypeID.h"
#include "MobileElement.h"

namespace state {

  /// class Settlers - 
  class Settlers : public state::MobileElement {
    // Operations
  public:
    TypeID getTypeID ();
    bool const equals (const Element& other);
    Settlers ();
    bool const isMoving ();
    // Setters and Getters
  };

};

#endif
