// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class StaticElement - 
  class StaticElement : public state::Element {
    // Attributes
  protected:
    bool accessible;
    // Operations
  public:
    virtual bool isAccessible () const = 0;
    // Setters and Getters
    bool getAccessible() const;
    void setAccessible(bool accessible);
  };

};

#endif
