// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class StaticElement - 
  class StaticElement : public state::Element {
    // Attributes
  public:
    int accessible;
    // Operations
  public:
    //bool const equals (const Element& other);
    // Setters and Getters
  };

};

#endif
