// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeID {
    LANDSCAPE     = 1,
    CITY     = 2,
    ARMY     = 3,
    SETTLERS     = 4
  };

};

#endif
