// Generated by dia2code
#ifndef RENDER__CHARACTERSLAYER__H
#define RENDER__CHARACTERSLAYER__H


namespace state {
  class Layer;
};
namespace render {
  class RenderLayer;
}

#include "RenderLayer.h"
#include "state/Layer.h"

namespace render {

  /// class CharactersLayer - 
  class CharactersLayer : public render::RenderLayer {
    // Associations
    // Attributes
  protected:
    const state::Layer& tab;
    // Operations
  public:
    CharactersLayer (const state::Layer& tab);
    void initDrawer ();
    // Setters and Getters
    const state::Layer& getTab() const;
  };

};

#endif
