// Generated by dia2code
#ifndef RENDER__CHARACTERSSET__H
#define RENDER__CHARACTERSSET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class CharactersSet - 
  class CharactersSet : public render::TileSet {
    // Attributes
  protected:
    std::vector<Tile> characters;
    // Operations
  public:
    CharactersSet ();
    const std::string getFile () const;
    int getWidth () const;
    int getHeight () const;
    const Tile& getTile (const state::Element& e) const;
    // Setters and Getters
    const std::vector<Tile>& getCharacters() const;
    void setCharacters(const std::vector<Tile>& characters);
  };

};

#endif
