// Generated by dia2code
#ifndef RENDER__DRAWER__H
#define RENDER__DRAWER__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {
  class Tile;
};
namespace sf {
  class Transformable;
  class Drawable;
}


namespace render {

  /// class Drawer - 
  class Drawer : public sf::Transformable, public sf::Drawable {
    // Attributes
  private:
    sf::VertexArray m_vertices;
    sf::Texture m_tileset;
    // Operations
  public:
    void loadTexture (const std::string fileName);
    void initVertex (int width, int height);
    virtual void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    void setVertexLocation (int i, int x, int y);
    void setVertexTexture (int i, const Tile& tex);
    // Setters and Getters
  };

};

#endif
