// Generated by dia2code
#ifndef RENDER__RENDERLAYER__H
#define RENDER__RENDERLAYER__H


namespace render {
  class Drawer;
  class TileSet;
}

#include "TileSet.h"
#include "Drawer.h"

namespace render {

  /// class RenderLayer - 
  class RenderLayer {
    // Associations
    // Attributes
  protected:
    Drawer* drawer;
    TileSet* tileSet;
    // Operations
  public:
    virtual ~RenderLayer ();
    virtual void initDrawer () = 0;
    Drawer* getDrawer () const;
    void setDrawer (Drawer* drawer);
    // Setters and Getters
    const TileSet*& getTileSet() const;
    void setTileSet(const TileSet*& tileSet);
  };

};

#endif
