// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
}

namespace render {

  /// class TileSet - 
  class TileSet {
    // Operations
  public:
    virtual const std::string getFile () const = 0;
    virtual const Tile& getTile (const state::Element& e) const = 0;
    virtual int getWidth () const = 0;
    virtual int getHeight () const = 0;
    virtual ~TileSet ();
    // Setters and Getters
  };

};

#endif
