// Generated by dia2code
#ifndef RENDER__TILEMAP__H
#define RENDER__TILEMAP__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Transformable;
  class Drawable;
}


namespace render {

  /// class TileMap - 
  class TileMap : public sf::Transformable, public sf::Drawable {
    // Attributes
  private:
    sf::VertexArray m_vertices;
    sf::Texture m_tileset;
    // Operations
  public:
    bool load (const std::string& tileset, const int* tiles);
    virtual void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    bool loadLayer (const std::string& layer);
    // Setters and Getters
  };

};

#endif
