// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H


namespace state {
  class State;
};
namespace engine {
  class Engine;
  class Command;
}

#include "engine/Engine.h"
#include "engine/Command.h"
#include "state/State.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  protected:
    state::State& state;
    engine::Engine& engine;
    // Operations
  public:
    virtual void run (engine::Engine& engine) = 0;
    AI (state::State& state, engine::Engine& engine);
    // Setters and Getters
    state::State& getState() const;
    void setState(const state::State&& state);
    engine::Engine& getEngine() const;
    void setEngine(const engine::Engine&& engine);
  };

};

#endif
