// Generated by dia2code
#ifndef AI__COMMANDSWEIGHTS__H
#define AI__COMMANDSWEIGHTS__H


namespace engine {
  class Command;
}

namespace ai {

  /// class CommandsWeights - 
  class CommandsWeights {
    // Attributes
  protected:
    engine::Command* command;
    int weight;
    // Operations
  public:
    CommandsWeights (engine::Command* command, int weight);
    engine::Command* getCommand () const;
    // Setters and Getters
    void setCommand(const engine::Command*& command);
    int getWeight() const;
    void setWeight(int weight);
  };

};

#endif
