// Generated by dia2code
#ifndef AI__NODE__H
#define AI__NODE__H

#include <vector>

namespace ai {
  class Node;
}

namespace ai {

  /// class Node - 
  class Node {
    // Attributes
  protected:
    int prof;
    std::vector<Node*> sons;
    Node* father;
    int value;
    // Operations
  public:
    Node ();
    // Setters and Getters
    int getProf() const;
    void setProf(int prof);
    const std::vector<Node*>& getSons() const;
    void setSons(const std::vector<Node*>& sons);
    const Node*& getFather() const;
    void setFather(const Node*& father);
    int getValue() const;
    void setValue(int value);
  };

};

#endif
