// Generated by dia2code
#ifndef AI__NODE__H
#define AI__NODE__H

#include <vector>

namespace ai {
  class Node;
};
namespace engine {
  class Command;
}

namespace ai {

  /// class Node - 
  class Node {
    // Attributes
  protected:
    int prof;
    std::vector<Node*> sons;
    Node* father;
    int value;
    engine::Command* command;
    // Operations
  public:
    Node ();
    Node (int prof, int value, engine::Command* command);
    void addSon (Node* node);
    Node* getSon (int id) const;
    int getSize () const;
    engine::Command* getCommand () const;
    // Setters and Getters
    int getProf() const;
    void setProf(int prof);
    const std::vector<Node*>& getSons() const;
    void setSons(const std::vector<Node*>& sons);
    const Node*& getFather() const;
    void setFather(const Node*& father);
    int getValue() const;
    void setValue(int value);
    void setCommand(const engine::Command*& command);
  };

};

#endif
