// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H


namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Operations
  public:
    RandomAI (state::State& state, engine::Engine& engine);
    void run (engine::Engine& engine);
    // Setters and Getters
  };

};

#endif
