// Generated by dia2code
#ifndef ENGINE__ARMYFUSIONCOMMAND__H
#define ENGINE__ARMYFUSIONCOMMAND__H

#include <stack>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class ArmyFusionCommand;
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class ArmyFusionCommand - 
  class ArmyFusionCommand : public engine::Command {
    // Attributes
  protected:
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    // Operations
  public:
    ArmyFusionCommand (int xFrom, int yFrom, int xTo, int yTo);
    void execute (state::State& state, std::stack<Action*>& actionStack);
    CommandTypeId getCommandTypeId () const;
    void serialize (Json::Value& out) const;
    ArmyFusionCommand* deserialize (const Json::Value& in);
    // Setters and Getters
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
  };

};

#endif
