// Generated by dia2code
#ifndef ENGINE__ATTACKCITYCOMMAND__H
#define ENGINE__ATTACKCITYCOMMAND__H

#include <stack>

namespace state {
  class State;
};
namespace engine {
  class Action;
};
namespace state {
  class Army;
  class City;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class AttackCityCommand - 
  class AttackCityCommand : public engine::Command {
    // Attributes
  protected:
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    // Operations
  public:
    AttackCityCommand (int xFrom, int yFrom, int xTo, int yTo);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state, std::stack<Action*>& actionStack);
    bool solveCityAttack (state::Army* army, state::City* city);
    // Setters and Getters
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
  };

};

#endif
