// Generated by dia2code
#ifndef ENGINE__ATTACKCITYACTION__H
#define ENGINE__ATTACKCITYACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class AttackCityAction - 
  class AttackCityAction : public engine::Action {
    // Attributes
  protected:
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    int playerA;
    int playerB;
    int soldiersAttacker;
    int soldiersCity;
    int defense;
    bool free;
    // Operations
  public:
    AttackCityAction (int xFrom, int yFrom, int xTo, int yTo, int playerA, int playerB, int soldiersAttacker, int soldiersCity, int defense, bool free);
    void undo (state::State& state);
    // Setters and Getters
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
    int getPlayerA() const;
    void setPlayerA(int playerA);
    int getPlayerB() const;
    void setPlayerB(int playerB);
    int getSoldiersAttacker() const;
    void setSoldiersAttacker(int soldiersAttacker);
    int getSoldiersCity() const;
    void setSoldiersCity(int soldiersCity);
    int getDefense() const;
    void setDefense(int defense);
    bool getFree() const;
    void setFree(bool free);
  };

};

#endif
