// Generated by dia2code
#ifndef ENGINE__ATTACKARMYACTION__H
#define ENGINE__ATTACKARMYACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class AttackArmyAction - 
  class AttackArmyAction : public engine::Action {
    // Attributes
  protected:
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    int soldiersAttacker;
    int soldiersAttacked;
    int playerA;
    int playerB;
    // Operations
  public:
    AttackArmyAction (int xFrom, int yFrom, int xTo, int yTo, int soldiersAttackers, int soldiersAttacked, int player, int playerB);
    void undo (state::State& state);
    // Setters and Getters
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
    int getSoldiersAttacker() const;
    void setSoldiersAttacker(int soldiersAttacker);
    int getSoldiersAttacked() const;
    void setSoldiersAttacked(int soldiersAttacked);
    int getPlayerA() const;
    void setPlayerA(int playerA);
    int getPlayerB() const;
    void setPlayerB(int playerB);
  };

};

#endif
