// Generated by dia2code
#ifndef ENGINE__ATTACKARMYCOMMAND__H
#define ENGINE__ATTACKARMYCOMMAND__H

#include <stack>

namespace state {
  class State;
};
namespace engine {
  class Action;
};
namespace state {
  class Army;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class AttackArmyCommand - 
  class AttackArmyCommand : public engine::Command {
    // Attributes
  protected:
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    // Operations
  public:
    AttackArmyCommand (int xFrom, int yFrom, int xTo, int yTo);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state, std::stack<Action*>& actionStack);
    bool solveFightArmy (state::Army* firstArmy, state::Army* secondArmy);
    // Setters and Getters
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
  };

};

#endif
