// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    MOVECHAR     = 1,
    CONSTRUCT     = 2,
    UPGRADE     = 3,
    EOT     = 4,
    ATTACKARMY     = 5,
    ATTACKCITY     = 6,
    FUSIONARMY     = 7,
    LEAVECITY     = 8,
    SPLITARMY     = 9,
    ENTERCITY     = 10,
    MAKESOLDIERS     = 11
  };

};

#endif
