// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    MOVECHAR     = 1,
    CONSTRUCT     = 2,
    UPGRADE     = 3
  };

};

#endif
