// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <stack>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class Command;
};
namespace state {
  class Element;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "state/Element.h"
#include "state/State.h"

namespace engine {

  /// class Command - 
  class Command {
    // Operations
  public:
    virtual ~Command ();
    virtual CommandTypeId getCommandTypeId () const = 0;
    virtual void execute (state::State& state, std::stack<Action*>& actionStack) = 0;
    virtual void serialize (Json::Value& out) const = 0;
    Command* deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
