// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


namespace state {
  class State;
  class Element;
}

#include "CommandTypeId.h"
#include "state/Element.h"
#include "state/State.h"

namespace engine {

  /// class Command - 
  class Command {
    // Operations
  public:
    virtual ~Command ();
    virtual CommandTypeId getCommandTypeId () const = 0;
    virtual void execute (state::State& state) = 0;
    // Setters and Getters
  };

};

#endif
