// Generated by dia2code
#ifndef ENGINE__CONSTRUCTACTION__H
#define ENGINE__CONSTRUCTACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
};
namespace state {
  class City;
}

#include "Action.h"
#include "state/City.h"

namespace engine {

  /// class ConstructAction - 
  class ConstructAction : public engine::Action {
    // Attributes
  protected:
    int x;
    int y;
    state::Construction* construction;
    // Operations
  public:
    ConstructAction (int x, int y, state::Construction* construction);
    void undo (state::State& state);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    const state::Construction*& getConstruction() const;
    void setConstruction(const state::Construction*& construction);
  };

};

#endif
