// Generated by dia2code
#ifndef ENGINE__ENDOFTURNACTION__H
#define ENGINE__ENDOFTURNACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class EndOfTurnAction - 
  class EndOfTurnAction : public engine::Action {
    // Operations
  public:
    EndOfTurnAction ();
    void undo (state::State& state);
    // Setters and Getters
  };

};

#endif
