// Generated by dia2code
#ifndef ENGINE__ENDOFTURNCOMMAND__H
#define ENGINE__ENDOFTURNCOMMAND__H

#include <stack>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class EndOfTurnCommand - 
  class EndOfTurnCommand : public engine::Command {
    // Operations
  public:
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state, std::stack<Action*>& actionStack);
    EndOfTurnCommand ();
    // Setters and Getters
  };

};

#endif
