// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>
#include <stack>

namespace state {
  class State;
};
namespace engine {
  class Command;
  class Action;
}

#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  private:
    state::State& currentState;
    std::vector<Command*> currentCommands;
    // Operations
  public:
    Engine (state::State& state);
    ~Engine ();
    void addCommand (Command* command);
    void addPassiveCommand ();
    void Update ();
    void runCommand (Command* command, std::stack<Action*>& actionStack);
    const state::State& getState () const;
    void undo (std::stack<Action*>& actionStack);
    // Setters and Getters
  };

};

#endif
