// Generated by dia2code
#ifndef ENGINE__ENTERCITYCOMMAND__H
#define ENGINE__ENTERCITYCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class EnterCityCommand - 
  class EnterCityCommand : public engine::Command {
    // Attributes
  protected:
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    int soldiers;
    // Operations
  public:
    EnterCityCommand (int xFrom, int yFrom, int xTo, int yTo, int soldiers);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
    int getSoldiers() const;
    void setSoldiers(int soldiers);
  };

};

#endif
