// Generated by dia2code
#ifndef ENGINE__MAKESOLDIERSCOMMAND__H
#define ENGINE__MAKESOLDIERSCOMMAND__H

#include <stack>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class MakeSoldiersCommand;
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class MakeSoldiersCommand - 
  class MakeSoldiersCommand : public engine::Command {
    // Attributes
  protected:
    int x;
    int y;
    // Operations
  public:
    MakeSoldiersCommand (int x, int y);
    CommandTypeId getCommandTypeId () const;
    void execute (state::State& state, std::stack<Action*>& actionStack);
    void serialize (Json::Value& out) const;
    MakeSoldiersCommand* deserialize (const Json::Value& in);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
  };

};

#endif
