// Generated by dia2code
#ifndef ENGINE__MOVECHARACTION__H
#define ENGINE__MOVECHARACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class MoveCharAction - 
  class MoveCharAction : public engine::Action {
    // Attributes
  protected:
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    // Operations
  public:
    void undo (state::State& state);
    MoveCharAction (int xFrom, int yFrom, int xTo, int yTo);
    // Setters and Getters
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
  };

};

#endif
