// Generated by dia2code
#ifndef ENGINE__SPLITARMYACTION__H
#define ENGINE__SPLITARMYACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class SplitArmyAction - 
  class SplitArmyAction : public engine::Action {
    // Attributes
  protected:
    int xFrom;
    int yFrom;
    int xTo;
    int yTo;
    int soldiers;
    // Operations
  public:
    SplitArmyAction (int xFrom, int yFrom, int xTo, int yTo, int soldiers);
    void undo (state::State& state);
    // Setters and Getters
    int getXFrom() const;
    void setXFrom(int xFrom);
    int getYFrom() const;
    void setYFrom(int yFrom);
    int getXTo() const;
    void setXTo(int xTo);
    int getYTo() const;
    void setYTo(int yTo);
    int getSoldiers() const;
    void setSoldiers(int soldiers);
  };

};

#endif
