// Generated by dia2code
#ifndef SERVER__COMMANDSSERVICE__H
#define SERVER__COMMANDSSERVICE__H

#include <json/json.h>

namespace server {
  class Game;
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class CommandsService - 
  class CommandsService : public server::AbstractService {
    // Attributes
  protected:
    Game& game;
    // Operations
  public:
    CommandsService (Game& game);
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus put (Json::Value& out, const Json::Value& in);
    // Setters and Getters
    Game& getGame() const;
    void setGame(const Game&& game);
  };

};

#endif
