// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H

#include <vector>
#include <json/json.h>

namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  protected:
    std::vector<Player*> players;
    int playersLimit;
    int idPlayer;
    Json::Value currentCommands;
    // Operations
  public:
    Game (int playersLimit, Json::Value commands);
    Player* player (int i);
    int addPlayer (Player* player);
    void removePlayer (int id);
    bool isFullOfPlayers ();
    void clearCommands ();
    // Setters and Getters
    const std::vector<Player*>& getPlayers() const;
    void setPlayers(const std::vector<Player*>& players);
    int getPlayersLimit() const;
    void setPlayersLimit(int playersLimit);
    int getIdPlayer() const;
    void setIdPlayer(int idPlayer);
    const Json::Value& getCurrentCommands() const;
    void setCurrentCommands(const Json::Value& currentCommands);
  };

};

#endif
