// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.h"
#include "engine/Command.h"
#include "engine/Engine.h"
#include "engine/MoveCharCommand.h"
#include "engine/ConstructCommand.h"
#include "engine/UpgradeCommand.h"
#include "engine/EndOfTurnCommand.h"
#include "engine/AttackArmyCommand.h"
#include "engine/AttackCityCommand.h"
#include "engine/ArmyFusionCommand.h"
#include "engine/LeaveCityCommand.h"
#endif
