// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <SFML/Graphics.hpp>

namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "engine/Engine.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  protected:
    engine::Engine engine;
    ai::AI* player1AI;
    ai::AI* player2AI;
    state::State& state;
    // Operations
  public:
    Client (state::State& state);
    void engineUpdating ();
    void engineUpdated ();
    void run (sf::RenderWindow& window);
    // Setters and Getters
    const engine::Engine& getEngine() const;
    void setEngine(const engine::Engine& engine);
    const ai::AI*& getPlayer1AI() const;
    void setPlayer1AI(const ai::AI*& player1AI);
    const ai::AI*& getPlayer2AI() const;
    void setPlayer2AI(const ai::AI*& player2AI);
    state::State& getState() const;
    void setState(const state::State&& state);
  };

};

#endif
