// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/Drawer.h"
#include "render/TileSet.h"
#include "render/Tile.h"
#include "render/RenderLayer.h"
#include "render/MapLayer.h"
#include "render/MapSet.h"
#include "render/CharactersLayer.h"
#include "render/CharactersSet.h"
#endif
